 QUERY:
 1)SELECT * FROM MEAL
  WHERE PRICE > 15;
 2)SELECT * FROM INGREDIENTS
   WHERE VEGETARIAN;
 3)SELECT * FROM MEAL
   WHERE CALORIES > 500;
 4)SELECT * FROM MEAL
   WHERE PRICE > 15 AND PRICE < 16;
 5)SELECT * FROM INGREDIENTS
   WHERE !CONTAINS_LACTOSE AND GLUTEN_FREE;
 6)SELECT * FROM MEAL
   WHERE PRICE < 15 OR CALORIES > 600;
 7)SELECT * FROM INGREDIENTS
   WHERE VEGAN OR GLUTEN_FREE;
 8)SELECT * FROM MEAL
   WHERE NAME ='PASTA PESTO';
 9)SELECT * FROM INGREDIENTS
   WHERE !CONTEINS_LACTOSE;
 10)SELECT * FROM MEAL
    WHERE PRICE > 20 AND CALORIES < 800;