1)CREATE TABLE CHEAP_MEAL AS
  SELECT * FROM MEAL WHERE PRICE < 15;

2)CREATE TABLE VEGAN_INGREDIENT AS
  SELECT * FROM INGREDIENT WHERE FALSE;

  INSERT INTO VEGAN_INGREDIENT
  SELECT * FROM INGREDIENT WHERE VEGAN;

3)CREATE VIEW EXPENSIVE_MEAL AS
  SELECT * FROM MEAL WHERE PRICE > 15;

4)CREATE VIEW LACTOSE_FREE_INGREDIENT AS
  SELECT * FROM INGREDIENT WHERE !CONTAINS_LACTOSE;

5)CREATE TABLE HIGH_CALORIE_MEAL AS
  SELECT * FROM MEAL WHERE CALORIES > 650;