
ALTER TABLE INGREDIENTS
ADD CONSTRAINT UNIQUE(NAME);

ALTER TABLE INGREDIENTS
MODIFY VEGETARIAN BOOLEAN NOT NULL;

ALTER TABLE INGREDIENTS
MODIFY VEGAN BOOLEAN NOT NULL;

ALTER TABLE INGREDIENTS
MODIFY CONTAINS_LACTOSE BOOLEAN NOT NULL;

ALTER TABLE INGREDIENTS
MODIFY GLUTEN_FREE BOOLEAN NOT NULL;